/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Public: what the SPA needs to start an AuthKit login.
         *
         *     Unauthenticated by design — the browser has to read this *before* it has a token.
         *     It exposes only the client id and issuer, both of which are public values in an
         *     OAuth public-client flow. No secret is involved; AuthKit is PKCE-only here.
         */
        get: operations["authConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food-facts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food Facts */
        get: operations["searchFoodFacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Nutrition Calendar */
        get: operations["getNutritionCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Nutrition Day */
        get: operations["getNutritionDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goals */
        get: operations["getGoals"];
        /** Set Goals */
        put: operations["setGoals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Nutrition */
        post: operations["logNutrition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/logs/amend-last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Amend Last Log */
        post: operations["amendLastLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Nutrition Log */
        patch: operations["updateNutritionLog"];
        trace?: never;
    };
    "/api/nutrition/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meal Templates */
        get: operations["listMealTemplates"];
        put?: never;
        /** Save Meal Template */
        post: operations["saveMealTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Meal Template */
        delete: operations["deleteMealTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/templates/{template_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Meal Template Item */
        patch: operations["updateMealTemplateItem"];
        trace?: never;
    };
    "/api/nutrition/templates/{template_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Meal Template */
        post: operations["logMealTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutrition/trackable-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trackable Types */
        get: operations["listTrackableTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Partner */
        get: operations["getPartnerSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Invite */
        post: operations["generatePartnerInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/invite/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invite Preview
         * @description Unauthenticated by design — no `CurrentUser`/`CurrentPrincipal` parameter, same
         *     pattern as `/auth/config`. An unauthenticated visitor has to see this before
         *     signing up, and never anything more than a name and a validity flag.
         */
        get: operations["getPartnerInvitePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Invite */
        post: operations["redeemPartnerInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planned Workouts */
        get: operations["getPlannedWorkouts"];
        put?: never;
        /** Plan Workout */
        post: operations["planWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts/{planned_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Planned Workout */
        post: operations["updatePlannedWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/profile/complete-onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tdee/calculate-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Targets */
        post: operations["calculateTargets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workout Templates */
        get: operations["listWorkoutTemplates"];
        put?: never;
        /** Create Workout Template */
        post: operations["createWorkoutTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout Template */
        get: operations["getWorkoutTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Workout Template */
        post: operations["archiveWorkoutTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Workout Template */
        post: operations["updateWorkoutTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weekly-pattern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Pattern */
        get: operations["getWeeklyPattern"];
        /** Set Weekly Pattern */
        put: operations["setWeeklyPattern"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description The auth spike's REST half. If this returns your WorkOS sub, the browser flow works.
         *
         *     email/first_name/last_name come from the environment's JWT template — they're custom
         *     claims, not defaults, so a missing email means the template got dropped in WorkOS.
         *
         *     Also syncs `UserProfile.display_name` from these same claims (#5, Partner v1) —
         *     every authenticated SPA session calls this on load, which is the only place a
         *     user's own current name is available to persist for a future partner to read.
         */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout History */
        get: operations["getWorkoutHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Workout */
        get: operations["getActiveWorkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["listWorkoutExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Workout */
        post: operations["logWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/log-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Activity */
        post: operations["logActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/log-set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Set */
        post: operations["logSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Workout */
        post: operations["startWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout Streak */
        get: operations["getWorkoutStreak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Workout Entry */
        post: operations["updateWorkoutEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Workout */
        post: operations["finishWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout Live */
        get: operations["getWorkoutLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only — deliberately does not touch the database.
         *
         *     Railway gates its blue-green cutover on this. If it depended on Postgres, a brief
         *     database blip would block deploys of code that has nothing to do with the database.
         *     Use /health/ready for the dependency check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityLevel
         * @enum {string}
         */
        ActivityLevel: "sedentary" | "light" | "moderate" | "active" | "very_active";
        /** AmendLastLogOut */
        AmendLastLogOut: {
            /** Deleted */
            deleted: boolean;
            log?: components["schemas"]["NutritionLogOut"] | null;
        };
        /** AuthConfigOut */
        AuthConfigOut: {
            /** Authkit Domain */
            authkit_domain: string;
            /** Client Id */
            client_id: string;
            /** Configured */
            configured: boolean;
            /** Environment */
            environment: string;
            /** Redirect Uri */
            redirect_uri: string;
            /** Resource */
            resource: string;
        };
        /**
         * BiologicalSex
         * @enum {string}
         */
        BiologicalSex: "male" | "female";
        /** CalculateTargetsResponse */
        CalculateTargetsResponse: {
            /** Calories */
            calories: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
            /** Protein G */
            protein_g: number;
            /** Tdee */
            tdee: number;
        };
        /** CelebrationOut */
        CelebrationOut: {
            /** Exercise Name */
            exercise_name: string;
            /** Kind */
            kind: string;
            /** Previous */
            previous: string | null;
            /** Value */
            value: string;
        };
        /** CreateTemplateExerciseIn */
        CreateTemplateExerciseIn: {
            /** Exercise */
            exercise: string;
            /** Group */
            group?: number | null;
            /** Notes */
            notes?: string | null;
            /** Reps */
            reps?: number | null;
            /** Seconds */
            seconds?: number | null;
            /** Sets */
            sets: number;
            /** Weight */
            weight?: number | string | null;
        };
        /** CreateWorkoutTemplateRequest */
        CreateWorkoutTemplateRequest: {
            /** Exercises */
            exercises: components["schemas"]["CreateTemplateExerciseIn"][];
            /** Name */
            name: string;
        };
        /** DayLogItemOut */
        DayLogItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** DayLogOut */
        DayLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["DayLogItemOut"][];
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Meal Type */
            meal_type: string | null;
            /** Name */
            name: string | null;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** ExerciseEntryIn */
        ExerciseEntryIn: {
            /** Exercise */
            exercise: string;
            /** Muscle Group */
            muscle_group?: string | null;
            /** Next Time Note */
            next_time_note?: string | null;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets: components["schemas"]["SetIn"][];
        };
        /** ExerciseEntryOut */
        ExerciseEntryOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            last_time?: components["schemas"]["LastTimeOut"] | null;
            /** Next Time Note */
            next_time_note: string | null;
            /** Notes */
            notes: string | null;
            /** Sets */
            sets: components["schemas"]["SetOut"][];
            /** Superset Group */
            superset_group?: number | null;
            target?: components["schemas"]["TargetOut"] | null;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Muscle Group */
            muscle_group: string;
            /** Name */
            name: string;
        };
        /** FinishWorkoutRequest */
        FinishWorkoutRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** FoodFactOut */
        FoodFactOut: {
            /** Brand */
            brand: string | null;
            /** Calories */
            calories: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Fiber G */
            fiber_g: number | null;
            /** Name */
            name: string;
            /** Protein G */
            protein_g: number | null;
            /** Serving Description */
            serving_description: string;
        };
        /** GoalIn */
        GoalIn: {
            /** Is Streak Target */
            is_streak_target?: boolean | null;
            /** Target Value */
            target_value: number | string;
            /** Trackable Key */
            trackable_key: string;
        };
        /** GoalOut */
        GoalOut: {
            /** Is Streak Target */
            is_streak_target: boolean;
            /** Period */
            period: string;
            /** Target Value */
            target_value: string;
            /** Trackable Key */
            trackable_key: string;
        };
        /**
         * GoalType
         * @enum {string}
         */
        GoalType: "lose_weight" | "maintain" | "gain_muscle" | "recomp";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitePreviewOut */
        InvitePreviewOut: {
            /** Inviter Display Name */
            inviter_display_name: string | null;
            /** Valid */
            valid: boolean;
        };
        /** LastTimeOut */
        LastTimeOut: {
            /** Note */
            note: string | null;
            /** Sets */
            sets: components["schemas"]["LastTimeSetOut"][];
        };
        /** LastTimeSetOut */
        LastTimeSetOut: {
            /** Reps */
            reps: number | null;
            /** Weight */
            weight: string | null;
        };
        /** LogActivityRequest */
        LogActivityRequest: {
            /** Activity Type */
            activity_type: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Logged At */
            logged_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Title */
            title?: string | null;
        };
        /** LogMealTemplateRequest */
        LogMealTemplateRequest: {
            /** Logged At */
            logged_at?: string | null;
            /** Meal Type */
            meal_type?: string | null;
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number | string;
        };
        /** LogNutritionRequest */
        LogNutritionRequest: {
            /** Entries */
            entries: components["schemas"]["NutritionEntryIn"][];
            /** Logged At */
            logged_at?: string | null;
            /** Meal Type */
            meal_type?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** LogOut */
        LogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Meal Type */
            meal_type: string | null;
            /** Name */
            name: string | null;
        };
        /** LogSetRequest */
        LogSetRequest: {
            /** Continue Session */
            continue_session?: boolean | null;
            /** Exercise */
            exercise: string;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
            /** Note */
            note?: string | null;
            /** Reps */
            reps?: number | null;
            /**
             * Set Type
             * @default reps
             */
            set_type: string;
            /**
             * Sets
             * @default 1
             */
            sets: number;
            /** Weight */
            weight?: number | string | null;
            /** Work Seconds */
            work_seconds?: number | null;
        };
        /** LogSetResponse */
        LogSetResponse: {
            /** Needs Clarification */
            needs_clarification?: string | null;
            workout?: components["schemas"]["WorkoutOut"] | null;
        };
        /** LogWorkoutRequest */
        LogWorkoutRequest: {
            /** Exercises */
            exercises: components["schemas"]["ExerciseEntryIn"][];
            /** Logged At */
            logged_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Title */
            title?: string | null;
        };
        /** MealTemplateItemOut */
        MealTemplateItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Serving Description */
            serving_description: string | null;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** MealTemplateSummaryOut */
        MealTemplateSummaryOut: {
            /** Default Meal Type */
            default_meal_type: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["MealTemplateItemOut"][];
            /** Name */
            name: string;
            /** Totals */
            totals: {
                [key: string]: string;
            };
        };
        /** MuscleCoverageOut */
        MuscleCoverageOut: {
            /** Level */
            level: string;
            /** Muscle */
            muscle: string;
            /** Score */
            score: number;
        };
        /** NutritionCalendarDayOut */
        NutritionCalendarDayOut: {
            /** Bars */
            bars: components["schemas"]["TrackableProgressOut"][];
            /**
             * Date
             * Format: date
             */
            date: string;
            hero: components["schemas"]["TrackableProgressOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "hit" | "miss" | "no-data";
        };
        /** NutritionDayOut */
        NutritionDayOut: {
            /** Bars */
            bars: components["schemas"]["TrackableProgressOut"][];
            /**
             * Date
             * Format: date
             */
            date: string;
            hero: components["schemas"]["TrackableProgressOut"];
            /** Logs */
            logs: components["schemas"]["DayLogOut"][];
            /** Streak Key */
            streak_key: string | null;
            /** Templates */
            templates: components["schemas"]["MealTemplateSummaryOut"][];
        };
        /** NutritionEntryIn */
        NutritionEntryIn: {
            /** Trackable Key */
            trackable_key: string;
            /** Value */
            value: number | string;
        };
        /** NutritionLogOut */
        NutritionLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Meal Type */
            meal_type: string | null;
            /** Name */
            name: string | null;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** PartnerFrequencyOut */
        PartnerFrequencyOut: {
            /** Last Workout At */
            last_workout_at: string | null;
            /** Total Workouts */
            total_workouts: number;
            /** Workouts Last 30 Days */
            workouts_last_30_days: number;
            /** Workouts Last 7 Days */
            workouts_last_7_days: number;
        };
        /** PartnerInviteOut */
        PartnerInviteOut: {
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** PartnerPersonalRecordOut */
        PartnerPersonalRecordOut: {
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
            /** Exercise Name */
            exercise_name: string;
            kind: components["schemas"]["PersonalRecordKind"];
            /** Value */
            value: string;
        };
        /**
         * PartnerSummaryOut
         * @description The privacy boundary itself (#12, resolved) — every field here is an
         *     aggregate value. There is no field food logs or weight entries could travel
         *     through, so a careless future change to `services/partner.py` has nowhere to
         *     put that data even by accident.
         */
        PartnerSummaryOut: {
            frequency: components["schemas"]["PartnerFrequencyOut"];
            /** Nutrition Streak */
            nutrition_streak: number;
            /** Partner Display Name */
            partner_display_name: string | null;
            /** Personal Records */
            personal_records: components["schemas"]["PartnerPersonalRecordOut"][];
            streak: components["schemas"]["StreakOut"];
        };
        /**
         * PersonalRecordKind
         * @enum {string}
         */
        PersonalRecordKind: "weight" | "e1rm";
        /** PlanWorkoutRequest */
        PlanWorkoutRequest: {
            /**
             * Scheduled For
             * Format: date
             */
            scheduled_for: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
        };
        /** PlannedWorkoutOut */
        PlannedWorkoutOut: {
            /** Exercise Names */
            exercise_names: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Scheduled For
             * Format: date
             */
            scheduled_for: string;
            status: components["schemas"]["PlannedWorkoutStatus"];
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Template Name */
            template_name: string;
            /** Workout Id */
            workout_id: string | null;
        };
        /**
         * PlannedWorkoutStatus
         * @enum {string}
         */
        PlannedWorkoutStatus: "planned" | "done" | "skipped";
        /** ProfileOut */
        ProfileOut: {
            activity_level: components["schemas"]["ActivityLevel"] | null;
            /** Age */
            age: number | null;
            /** Coach Notes */
            coach_notes: string | null;
            goal_type: components["schemas"]["GoalType"] | null;
            /** Height In */
            height_in: string | null;
            /** Onboarding Completed At */
            onboarding_completed_at: string | null;
            sex: components["schemas"]["BiologicalSex"] | null;
            weight_unit: components["schemas"]["WeightUnit"];
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            activity_level?: components["schemas"]["ActivityLevel"] | null;
            /** Age */
            age?: number | null;
            /** Coach Notes */
            coach_notes?: string | null;
            goal_type?: components["schemas"]["GoalType"] | null;
            /** Height In */
            height_in?: number | string | null;
            sex?: components["schemas"]["BiologicalSex"] | null;
            weight_unit?: components["schemas"]["WeightUnit"] | null;
        };
        /** RedeemInviteRequest */
        RedeemInviteRequest: {
            /** Code */
            code: string;
        };
        /** SaveMealTemplateRequest */
        SaveMealTemplateRequest: {
            /** Default Meal Type */
            default_meal_type?: string | null;
            /** Log Ids */
            log_ids: string[];
            /** Name */
            name: string;
            /** Template Id */
            template_id?: string | null;
        };
        /** SetGoalsRequest */
        SetGoalsRequest: {
            /** Goals */
            goals: components["schemas"]["GoalIn"][];
        };
        /** SetIn */
        SetIn: {
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
            /** Reps */
            reps?: number | null;
            /**
             * Set Type
             * @default reps
             */
            set_type: string;
            /** Weight */
            weight?: number | string | null;
            /** Work Seconds */
            work_seconds?: number | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Warmup */
            is_warmup: boolean;
            /** Reps */
            reps: number | null;
            /** Set Number */
            set_number: number;
            set_type: components["schemas"]["SetType"];
            /** Weight */
            weight: string | null;
            /** Work Seconds */
            work_seconds: number | null;
        };
        /**
         * SetType
         * @enum {string}
         */
        SetType: "reps" | "time";
        /** SetWeeklyPatternRequest */
        SetWeeklyPatternRequest: {
            /** Days */
            days: components["schemas"]["WeeklyPatternDayIn"][];
        };
        /** StartWorkoutRequest */
        StartWorkoutRequest: {
            /** Exercises */
            exercises?: string[] | null;
            /** Planned Id */
            planned_id?: string | null;
            /** Template Id */
            template_id?: string | null;
        };
        /** StreakOut */
        StreakOut: {
            /** Target */
            target: number;
            /** This Week */
            this_week: number;
            /** Weeks */
            weeks: number;
        };
        /** TargetOut */
        TargetOut: {
            /** Reps */
            reps: number | null;
            /** Seconds */
            seconds: number | null;
            /** Sets */
            sets: number;
            /** Weight */
            weight: string | null;
        };
        /** TemplateExerciseOut */
        TemplateExerciseOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string | null;
            /** Order Index */
            order_index: number;
            /** Reps */
            reps: number | null;
            /** Seconds */
            seconds: number | null;
            /** Sets */
            sets: number;
            /** Superset Group */
            superset_group: number | null;
            /** Weight */
            weight: string | null;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Archived At */
            archived_at: string | null;
            /** Description */
            description: string | null;
            /** Exercises */
            exercises: components["schemas"]["TemplateExerciseOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TrackableProgressOut */
        TrackableProgressOut: {
            /** Consumed */
            consumed: string;
            /** Label */
            label: string;
            /** Target */
            target: string | null;
            /** Trackable Key */
            trackable_key: string;
            /** Unit */
            unit: string;
        };
        /** TrackableTypeOut */
        TrackableTypeOut: {
            /** Category */
            category: string;
            /** Goal Eligible */
            goal_eligible: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
        };
        /** UpdateMealTemplateItemRequest */
        UpdateMealTemplateItemRequest: {
            /** Name */
            name: string;
            /** Serving Description */
            serving_description?: string | null;
            /** Values */
            values?: {
                [key: string]: number | string;
            };
        };
        /** UpdateNutritionLogRequest */
        UpdateNutritionLogRequest: {
            /** Meal Type */
            meal_type?: string | null;
            /** Name */
            name?: string | null;
            /** Values */
            values?: {
                [key: string]: number | string;
            } | null;
        };
        /** UpdatePlannedWorkoutRequest */
        UpdatePlannedWorkoutRequest: {
            /** Action */
            action: string;
        };
        /** UpdateWorkoutEntryRequest */
        UpdateWorkoutEntryRequest: {
            /** Action */
            action: string;
            /** Exercise */
            exercise?: string | null;
            /** Note */
            note?: string | null;
            /** Order */
            order?: string[] | null;
            /** Superset With */
            superset_with?: string | null;
            /** Workout Exercise Id */
            workout_exercise_id?: string | null;
        };
        /** UpdateWorkoutTemplateRequest */
        UpdateWorkoutTemplateRequest: {
            /** Action */
            action: string;
            /** Exercise */
            exercise?: string | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Order */
            order?: string[] | null;
            /** Reps */
            reps?: number | null;
            /** Seconds */
            seconds?: number | null;
            /** Sets */
            sets?: number | null;
            /** Superset With */
            superset_with?: string | null;
            /** Template Exercise Id */
            template_exercise_id?: string | null;
            /** Weight */
            weight?: number | string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyPatternDayIn */
        WeeklyPatternDayIn: {
            /** Day Of Week */
            day_of_week: number;
            /** Template Id */
            template_id?: string | null;
        };
        /** WeeklyPatternDayOut */
        WeeklyPatternDayOut: {
            /** Day Of Week */
            day_of_week: number;
            /** Template Id */
            template_id: string | null;
            /** Template Name */
            template_name: string | null;
        };
        /**
         * WeightUnit
         * @enum {string}
         */
        WeightUnit: "lbs" | "kg";
        /** WhoamiOut */
        WhoamiOut: {
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** User Sub */
            user_sub: string;
        };
        /** WorkoutGroupOut */
        WorkoutGroupOut: {
            /** Exercises */
            exercises: components["schemas"]["ExerciseEntryOut"][];
            /** Is Superset */
            is_superset: boolean;
            /** Superset Group */
            superset_group: number | null;
        };
        /** WorkoutLiveOut */
        WorkoutLiveOut: {
            /**
             * Celebrations
             * @default []
             */
            celebrations: components["schemas"]["CelebrationOut"][];
            /** Completed At */
            completed_at: string | null;
            /** Groups */
            groups: components["schemas"]["WorkoutGroupOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Muscle Coverage
             * @default []
             */
            muscle_coverage: components["schemas"]["MuscleCoverageOut"][];
            /** Notes */
            notes: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            streak?: components["schemas"]["StreakOut"] | null;
            /** Summary */
            summary: string;
        };
        /** WorkoutOut */
        WorkoutOut: {
            /** Activity Type */
            activity_type: string | null;
            /**
             * Celebrations
             * @default []
             */
            celebrations: components["schemas"]["CelebrationOut"][];
            /** Completed At */
            completed_at: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Exercises */
            exercises: components["schemas"]["ExerciseEntryOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string | null;
            /**
             * Resumed
             * @default false
             */
            resumed: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            streak?: components["schemas"]["StreakOut"] | null;
            /** Title */
            title: string | null;
            workout_type: components["schemas"]["WorkoutType"];
        };
        /**
         * WorkoutType
         * @enum {string}
         */
        WorkoutType: "strength" | "activity";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigOut"];
                };
            };
        };
    };
    searchFoodFacts: {
        parameters: {
            query?: {
                query?: string | null;
                barcode?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodFactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNutritionCalendar: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionCalendarDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNutritionDay: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionDayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"][];
                };
            };
        };
    };
    setGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetGoalsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logNutrition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogNutritionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    amendLastLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNutritionLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmendLastLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateNutritionLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNutritionLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMealTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTemplateSummaryOut"][];
                };
            };
        };
    };
    saveMealTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMealTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTemplateSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteMealTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateMealTemplateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealTemplateItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTemplateSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logMealTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogMealTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTrackableTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackableTypeOut"][];
                };
            };
        };
    };
    getPartnerSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerSummaryOut"] | null;
                };
            };
        };
    };
    generatePartnerInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerInviteOut"];
                };
            };
        };
    };
    getPartnerInvitePreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeemPartnerInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPlannedWorkouts: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanWorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updatePlannedWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlannedWorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    calculateTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateTargetsResponse"];
                };
            };
        };
    };
    listWorkoutTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
        };
    };
    createWorkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkoutTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getWorkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archiveWorkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateWorkoutTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkoutTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getWeeklyPattern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPatternDayOut"][];
                };
            };
        };
    };
    setWeeklyPattern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWeeklyPatternRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPatternDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiOut"];
                };
            };
        };
    };
    getWorkoutHistory: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                exercise?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getActiveWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"] | null;
                };
            };
        };
    };
    listWorkoutExercises: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
        };
    };
    logWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogWorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogActivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getWorkoutStreak: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakOut"];
                };
            };
        };
    };
    updateWorkoutEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkoutEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutLiveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finishWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishWorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getWorkoutLive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutLiveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
