"""tmpx template slice

Revision ID: 042c45622482
Revises:
Create Date: 2026-07-29 11:03:41.187168

Blue-green note: this runs while the previous release is still serving traffic. Additive
changes only — no drops or renames in the same deploy that stops using the column.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "042c45622482"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmpx_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tmpx_items")),
    )
    op.create_index(
        "ix_tmpx_items_user_id_created_at", "tmpx_items", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tmpx_items_user_id_created_at", table_name="tmpx_items")
    op.drop_table("tmpx_items")
    # ### end Alembic commands ###
