"""meal plan: planned meals and the kitchen tray

Revision ID: 991c39c7eaf7
Revises: a1c4e7f09b22
Create Date: 2026-09-28 11:40:53.145833

Blue-green note: additive only. Four new tables, nothing touched on the existing ones,
so the release running beside this one is unaffected.

`planned_meals` carries a unique `(user_id, scheduled_for, meal_type)` because a day's
breakfast slot holds exactly one meal. Planning into a full slot replaces what was
there, and the constraint is what makes that a fact about the data rather than a
convention the service layer has to keep remembering.

Both foreign keys out of `planned_meals` are SET NULL rather than CASCADE: deleting a
saved meal, or clearing the kitchen tray, must not silently blank a day that was already
planned. The row keeps the name it snapshotted, and `remove_kitchen_item` freezes the
resolved macros onto the plan before the tray entry goes.

Autogenerate also wanted to convert `logs.confidence` and `logs.raw_ai_response` from
JSON to JSONB. That is pre-existing drift between model and database, first noted in
d0563dd9088f and left alone in af364567dc8e for the same reason: it is unrelated to this
change, and rewriting a column type on a live table has no business riding along in a
deploy about meal planning.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "991c39c7eaf7"
down_revision: str | None = "a1c4e7f09b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kitchen_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "kind", sa.Enum("leftover", "ingredient", name="kitchen_item_kind"), nullable=False
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("portion", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_items")),
    )
    op.create_index("ix_kitchen_items_user_id", "kitchen_items", ["user_id"], unique=False)
    op.create_table(
        "kitchen_item_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kitchen_item_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kitchen_item_id"],
            ["kitchen_items.id"],
            name=op.f("fk_kitchen_item_templates_kitchen_item_id_kitchen_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["meal_templates.id"],
            name=op.f("fk_kitchen_item_templates_template_id_meal_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_item_templates")),
        sa.UniqueConstraint(
            "kitchen_item_id", "template_id", name="uq_kitchen_item_templates_kitchen_item_id"
        ),
    )
    op.create_table(
        "kitchen_item_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kitchen_item_id", sa.UUID(), nullable=False),
        sa.Column("trackable_key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kitchen_item_id"],
            ["kitchen_items.id"],
            name=op.f("fk_kitchen_item_values_kitchen_item_id_kitchen_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trackable_key"],
            ["trackable_types.key"],
            name=op.f("fk_kitchen_item_values_trackable_key_trackable_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kitchen_item_values")),
        sa.UniqueConstraint(
            "kitchen_item_id", "trackable_key", name="uq_kitchen_item_values_kitchen_item_id"
        ),
    )
    op.create_index(
        "ix_kitchen_item_values_kitchen_item_id",
        "kitchen_item_values",
        ["kitchen_item_id"],
        unique=False,
    )
    op.create_table(
        "planned_meals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=False),
        sa.Column("meal_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("kitchen_item_id", sa.UUID(), nullable=True),
        sa.Column("portion", sa.Numeric(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planned", "logged", "skipped", name="planned_meal_status"),
            nullable=False,
        ),
        sa.Column("log_group_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')",
            name=op.f("ck_planned_meals_meal_type_is_a_known_slot"),
        ),
        sa.ForeignKeyConstraint(
            ["kitchen_item_id"],
            ["kitchen_items.id"],
            name=op.f("fk_planned_meals_kitchen_item_id_kitchen_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["meal_templates.id"],
            name=op.f("fk_planned_meals_template_id_meal_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planned_meals")),
        sa.UniqueConstraint(
            "user_id", "scheduled_for", "meal_type", name="uq_planned_meals_user_id"
        ),
    )
    op.create_index(
        "ix_planned_meals_user_id_scheduled_for",
        "planned_meals",
        ["user_id", "scheduled_for"],
        unique=False,
    )
    op.create_table(
        "planned_meal_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("planned_meal_id", sa.UUID(), nullable=False),
        sa.Column("trackable_key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_meal_id"],
            ["planned_meals.id"],
            name=op.f("fk_planned_meal_values_planned_meal_id_planned_meals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trackable_key"],
            ["trackable_types.key"],
            name=op.f("fk_planned_meal_values_trackable_key_trackable_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planned_meal_values")),
        sa.UniqueConstraint(
            "planned_meal_id", "trackable_key", name="uq_planned_meal_values_planned_meal_id"
        ),
    )
    op.create_index(
        "ix_planned_meal_values_planned_meal_id",
        "planned_meal_values",
        ["planned_meal_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_planned_meal_values_planned_meal_id", table_name="planned_meal_values")
    op.drop_table("planned_meal_values")
    op.drop_index("ix_planned_meals_user_id_scheduled_for", table_name="planned_meals")
    op.drop_table("planned_meals")
    op.drop_index("ix_kitchen_item_values_kitchen_item_id", table_name="kitchen_item_values")
    op.drop_table("kitchen_item_values")
    op.drop_table("kitchen_item_templates")
    op.drop_index("ix_kitchen_items_user_id", table_name="kitchen_items")
    op.drop_table("kitchen_items")
    # ### end Alembic commands ###
